cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      base-url: https://fairydecos3.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB