cloud:
  aws:
    s3:
      bucket: fairydeco
      base-url: https://fairydeco.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB